/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel.java
 *
 * Created on 17-nov-2009, 15:55:18
 */

package temporizador;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Date;
import java.util.Timer;

/**
 *
 * @author profesor
 */
public class Panel extends javax.swing.JPanel {


    int x=50;//coordenada del círculo

    /** Creates new form Panel */
    public Panel() {
        //initComponents();
        this.setBackground(Color.red);
        this.setSize(400,300);
    }
    
    
    void iniciarTarea(){
        Timer t=new Timer();
        MiTarea tt=new MiTarea( this );
        t.schedule(tt, 500,10);
    }



    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.yellow);
        g.drawRect(50,50,300,100);
        g.setColor(Color.white);
        g.fillOval(x,50, 100, 100 );
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
