
/*CREACION DE TABLAS*/

CREATE TABLE EMPLEADO(
   NIF VARCHAR2(10),
   NOM VARCHAR2(20) NOT NULL,
   APE VARCHAR2(30) NOT NULL,
   DIR VARCHAR2(50) NOT NULL,
   TEL VARCHAR2(9) NOT NULL,
   CONSTRAINT PK_EMPLEADO PRIMARY KEY (NIF));

CREATE SEQUENCE S1INFORME
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   NOCYCLE
   ORDER
   NOCACHE;
   
   
CREATE TABLE INFORME(
   IDE NUMBER(6),
   TIPO_ERR VARCHAR2(20) NOT NULL,
   DESC_ERR VARCHAR2(50) NOT NULL,
   FECHA DATE NOT NULL,
   CONSTRAINT PK_INFORME PRIMARY KEY (IDE));