
/*APARTADO C*/

SET SERVEROUTPUT ON FORMAT WORD_WRAPPED;
DECLARE
  CONT NUMBER(1):=0;
  REG EMPLEADO.NIF%TYPE;
  IDEINFOR INFORME.IDE%TYPE;
  FECERROR INFORME.FECHA%TYPE;
BEGIN
   REG:='47465176F';
   SELECT COUNT(*) INTO (CONT) FROM EMPLEADO WHERE (NIF=REG);
   IF(CONT>=1) THEN 
         DELETE FROM EMPLEADO WHERE NIF=REG;
         DBMS_OUTPUT.PUT_LINE('ELEMENO ELIMINADO');
   ELSE
      DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENC0NTRO EL REGISTRO');
      SELECT SYSDATE INTO FECERROR FROM DUAL;
      SELECT S1INFORME.NEXTVAL INTO IDEINFOR FROM DUAL;
      INSERT INTO INFORME (IDE,TIPO_ERR,DESC_ERR,FECHA) VALUES (IDEINFOR,'TIPO5','NO SE ENCONTRO EL REGISTRO',FECERROR);
      
   END IF;
END;
/
