
/*APARTADO B*/

SET SERVEROUTPUT ON FORMAT WORD_WRAPPED;
DECLARE
  CONT NUMBER(1):=0;
  REG EMPLEADO.NIF%TYPE;
  IDEINFOR INFORME.IDE%TYPE;
  FECERROR INFORME.FECHA%TYPE;
  NOMBRE EMPLEADO.NOM%TYPE;
  APELLIDO EMPLEADO.APE%TYPE;
  CALLE EMPLEADO.DIR%TYPE;
  TEL EMPLEADO.TEL%TYPE;
BEGIN
   REG:='47465176F';
   NOMBRE:='manuel';
   APELLIDO:='gutierrez';
   CALLE:='calle de las rosas';
   TEL:='3245236';
   SELECT COUNT(*) INTO CONT FROM EMPLEADO WHERE (NIF=REG);
   IF(CONT>=1) THEN 
         NOMBRE:=UPPER(NOMBRE);
         APELLIDO:=UPPER(APELLIDO);
         CALLE:=UPPER(CALLE);
         DBMS_OUTPUT.PUT_LINE(' CAMBIO REALIZADO CON EXITO');
   ELSE
      DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENC0NTRO EL REGISTRO');
      SELECT SYSDATE INTO FECERROR FROM DUAL;
      SELECT S1INFORME.NEXTVAL INTO IDEINFOR FROM DUAL;
      INSERT INTO INFORME (IDE,TIPO_ERR,DESC_ERR,FECHA) VALUES (IDEINFOR,'TIPO4','NO SE ENCONTRO EL REGISTRO',FECERROR);
      
   END IF;
END;
/