package GUI;

import data.Cabeza;
import data.Cuerpo;
import data.Pierna;
import java.awt.Graphics;

/**
 *
 * @author Profesor
 */
public class MiPanel extends javax.swing.JPanel {
    Cuerpo cuerpo;
    Cabeza cabeza;
    Pierna p1;
    /**
     * Creates new form MiPanel
     */
    public MiPanel(Cuerpo f, Cabeza c,Pierna p1) {
        //initComponents();
        this.cuerpo=f;
        this.cabeza=c;
        this.p1=p1;
    }
    
    

    @Override
    protected void paintComponent(Graphics g) {              
        cabeza.pintar(g);
        cuerpo.pintar(g);
        p1.pintar(g);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
