

/* ***   DMLs EJERCICIO 2 ***  */

/* *** APARTADO DE ELIMINACION DE TABLAS *** */

DROP TYPE VARRAY_USU;
DROP TABLE TOPVEN CASCADE CONSTRAINTS;

/* *** APARTADO DE CREACION DE TABLAS *** */

CREATE OR REPLACE TYPE VARRAY_USU IS VARRAY(3) OF VARCHAR2(10);

CREATE TABLE TOPVEN(
  CODIGO VARCHAR2(8),
  USUARIOS  VARRAY_USU,
  PROCESADO NUMBER(1),
  CONSTRAINT PK_TOPVEN PRIMARY KEY (CODIGO)); 

/* *** APARTADO INSERTS *** */

INSERT INTO PEDIDO (CODPED,USR,PRECIO,IVA,TOTAL,FECHA,VALIDADA) VALUES (4,'USU3',20.4,0.5,20.9,'16/03/13',1);
INSERT INTO PEDIDO (CODPED,USR,PRECIO,IVA,TOTAL,FECHA,VALIDADA) VALUES (5,'USU4',100,0.5,100.5,'17/03/13',1);
INSERT INTO PEDIDO (CODPED,USR,PRECIO,IVA,TOTAL,FECHA,VALIDADA) VALUES (6,'USU5',150,0.5,150.5,'17/03/13',1);
INSERT INTO PEDIDO (CODPED,USR,PRECIO,IVA,TOTAL,FECHA,VALIDADA) VALUES (7,'USU5',150,0.5,9,'17/03/13',1);
INSERT INTO PEDIDO (CODPED,USR,PRECIO,IVA,TOTAL,FECHA,VALIDADA) VALUES (8,'USU1',7,0.5,7.5,'17/03/13',1);
