

   /**********************************
   *    PRACTICA Nº2 DE PL-SQL       *
   *    MANUEL GUTIERREZ TORRERO     *
   *    1º DAM                       *
   ***********************************
   */
   

/* ***   EJERCICIO 2 ***  */

SET SERVEROUTPUT ON FORMAT WORD_WRAPPED;
DECLARE  --DECLARACION 
  --DECLARACION DE TIPOS DE LISTAS DINAMICAS
  TYPE TIPO_USU IS TABLE OF USUARIO.USR%TYPE INDEX BY BINARY_INTEGER;
  TYPE TIPO_TOT IS TABLE OF PEDIDO.TOTAL%TYPE INDEX BY BINARY_INTEGER;
  --DECLARACION VARRAY PARA GUARDAR LOS 3 USUARIOS QUE MAS PEDIDOS HAN REALIZADO
  LISTA_TOPVEN VARRAY_USU;
  --DECLARACION DE LISTAS DINAMICAS
  LISTA_USU TIPO_USU;
  LISTA_TOT TIPO_TOT;
  --DECLARACION DE VARIABLES
  CONT_USU NUMBER(2);
  CONT_PED NUMBER(2);
  USU NUMBER(2);
  TOT NUMBER(2):=1;
  N NUMBER(1):=0;
  M NUMBER(1):=0;
  IND NUMBER(1):=0;
  MAYOR_TOT PEDIDO.TOTAL%TYPE;
  MAYOR_USU PEDIDO.USR%TYPE;
  AUX_TOT PEDIDO.TOTAL%TYPE;
  AUX_USU PEDIDO.USR%TYPE;
  VARRAY_AUX VARRAY_USU:=VARRAY_USU('','','');
  CODIGO VARCHAR(8);
  CONT_TOP NUMBER(2):=0;
  FECHA DATE;
  FECHA_CAD VARCHAR2(8);
BEGIN  --INICIO BLOQUE ANONIMO
   CONT_TOP:=0;
   SELECT ADD_MONTHS(SYSDATE,-1) INTO FECHA FROM DUAL;
   SELECT TO_CHAR(FECHA) INTO FECHA_CAD FROM DUAL;
   FECHA_CAD:=SUBSTR(FECHA_CAD,4,10);
   --DBMS_OUTPUT.PUT_LINE(FECHA_CAD);
   SELECT COUNT(*) INTO CONT_TOP FROM TOPVEN WHERE (CODIGO=FECHA_CAD);
   --DBMS_OUTPUT.PUT_LINE(CONT_TOP);

IF(CONT_TOP=0)  THEN  
   SELECT COUNT(*)  INTO CONT_USU
   FROM (SELECT USR FROM PEDIDO WHERE (VALIDADA=1) GROUP BY USR);

   IF(CONT_USU>0) THEN
  
      FOR USU IN 1..CONT_USU LOOP --FOR CARGA USUARIOS
            
        SELECT USR INTO LISTA_USU(USU)
        FROM (SELECT ROWNUM AS NUM,USR FROM 
             (SELECT USR FROM PEDIDO WHERE VALIDADA=1
              GROUP BY USR))
        WHERE NUM=USU; 
      
      END LOOP;
      TOT:=1;
      FOR USU IN 1..CONT_USU LOOP --FOR RECORRE USUARIOS
            --DBMS_OUTPUT.PUT_LINE(LISTA_USU(USU));
            
            SELECT COUNT(*) INTO CONT_PED
            FROM (SELECT CODPED FROM PEDIDO WHERE (VALIDADA=1) AND USR=LISTA_USU(USU));

            IF(CONT_PED>0) THEN
            
                  SELECT SUM(TOTAL) INTO LISTA_TOT(TOT) FROM PEDIDO WHERE (VALIDADA=1 AND USR=LISTA_USU(USU));
                  --DBMS_OUTPUT.PUT_LINE(LISTA_TOT(TOT));
                  TOT:=TOT+1;
              
            END IF;
     
      END LOOP;--FOR RECORRE USUARIOS
      /*
      DBMS_OUTPUT.PUT_LINE('SUMATORIOS');
      FOR N IN 1..TOT-1 LOOP
         DBMS_OUTPUT.PUT_LINE('USUS: '||LISTA_USU(N));
         DBMS_OUTPUT.PUT_LINE('SUM: '||LISTA_TOT(N));
      END LOOP;
      */
      
      FOR N IN 1..TOT-1 LOOP
         MAYOR_TOT:=0;
         FOR M IN N..TOT-1 LOOP
         
           IF(LISTA_TOT(M)>MAYOR_TOT) THEN
              MAYOR_TOT:=LISTA_TOT(M);
              MAYOR_USU:=LISTA_USU(M);
              IND:=M;
           END IF;
           
         END LOOP;
         AUX_TOT:=LISTA_TOT(N);
         AUX_USU:=LISTA_USU(N);
         LISTA_USU(N):=MAYOR_USU;
         LISTA_TOT(N):=MAYOR_TOT;
         LISTA_TOT(IND):=AUX_TOT;
         LISTA_USU(IND):=AUX_USU;
         
      END LOOP;
      /*
      DBMS_OUTPUT.PUT_LINE('SUMATORIOS ORDENADOS');
      FOR N IN 1..TOT-1 LOOP
         DBMS_OUTPUT.PUT_LINE('USUS: '||LISTA_USU(N));
         DBMS_OUTPUT.PUT_LINE('SUM: '||LISTA_TOT(N));
      END LOOP;
      */
     /*RELLENAR VARRAY CON LOS USUARIOS CORRECTOS*/
     VARRAY_AUX(1):=LISTA_USU(1);
     VARRAY_AUX(2):=LISTA_USU(2);
     VARRAY_AUX(3):=LISTA_USU(3);
    
     SELECT FECHA_CAD INTO CODIGO FROM DUAL; 
     INSERT INTO TOPVEN (CODIGO,USUARIOS,PROCESADO) VALUES (CODIGO,VARRAY_AUX,1);
     DBMS_OUTPUT.PUT_LINE(' *** TOPVEN REALIZADO *** ');
   END IF;


ELSE
    DBMS_OUTPUT.PUT_LINE(' *** YA SE PROCESO EL TOP VENTAS PARA ESTE MES *** ');
END IF;
END;
/
--FIN BLOQUE ANONIMO
