/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaSalida.java
 *
 * Created on 08-may-2013, 18:57:02
 */
package GUI;

import data.Pais;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author profesor
 */
public class VentanaSalida extends javax.swing.JFrame {
    Pais pais1,pais2;
    float media_pob;
    
    
    /** Creates new form VentanaSalida */
    public VentanaSalida(Pais p1,Pais p2,float media) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(300, 150);
        this.setTitle("ventana salida");
        pais1=p1;
        pais2=p2;
        media_pob=media;

         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setFont(new Font("Courier",Font.BOLD,12));
        g.drawString("Nombre pais mayor pob.: "+this.pais1.getNombre(), 10,50);
        g.drawString("Nombre pais menor pob.: "+this.pais2.getNombre(), 10,80);
        g.drawString("Media de poblaciones: "+this.media_pob+" habitantes", 10,110);
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
