package GUI;

import data.Animacion;
import data.Dummy;
import data.Proyectil;
import java.awt.Graphics;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 *
 * @author Profesor
 */
public class MiPanel extends javax.swing.JPanel {    
    
   private Animacion a;

    /**
     * Creates new form MiPanel
     */
    public MiPanel(Animacion a) {
        initComponents();
        this.a=a;
    }
    
    

    @Override
    public void paint(Graphics g) {
        super.paint(g);        
        
        g.drawImage(a.getImgFondo(),0,0, this.getWidth(),this.getHeight(), this);
        
        for (Iterator<Dummy> it = a.getListaDummys().iterator(); it.hasNext();) {
            Dummy objeto = it.next();    
            objeto.pintar(g);
        }        
        
        //Dibujo las bombas
        a.pintaProyectiles(g);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
